language: node_js
sudo: required
node_js:
  - "8"
services:
  - postgresql
env:
  global:
    - NODE_ENV=test
before_script:
  - psql -c 'CREATE DATABASE travis_test;' -U postgres

script:
  - npm run test

after_success:
  - npm run coveralls
