import sgMail from '@sendgrid/mail';

const sendEMail = (email, firstName, url) => {
  sgMail.setApiKey(process.env.SENDGRID_API_KEY);

  const msg = {
    to: email,
    from: process.env.PROJECT_EMAIL,
    subject: 'Verify Your Email',
    text: 'Welcome to Barefoot Nomad, please verify your email below',
    link: 'localhose:3000',
    html: `'<div style="width: 90%; margin: 5em auto; box-shadow: 0 0 10px rgba(0,0,0,.9);">
  <div>
      <div>
          <div style="background-color: #2084ba; height: 3rem; width: 100%">
              <h2 style="text-align: center; color: white; padding-top: 10px;">Barefoot Nomad</h2>
          </div>
          <h4 style="text-align: center">Hi! ${firstName}</h4>
      </div>
      <div style=" padding: 0px 20px 20px 20px">
          <div>
          <p>Please verify that your email is <strong>${email}</strong> when you signed up.</p>
          <p>Click on the button below to verify.</p>
          <button style="color: white; background-color: #2084ba; border: none; border-radius: 10px; text-align: center; padding: 10px;"><a  href="${url}" style="text-decoration: none; color: white;">Verify Account</a></button>
      </div>
      <div>
          <h3 style="text-align: center">Thank you</h3>
          <h3 style="text-align: center">Please do not reply, this is an autogenerated email.</h3>
      </div>
      </div>
  </div>
</div>`,
  };
  sgMail.send(msg);
  return true;
};

export default sendEMail;
